MYFACES-4760 QuarkusApplication.getELResolver() introduces data race (#1041)
QuarkusApplication.getELResolver() first sets (and exposes) the instance variable
and only then calls the resolver builder. The builder is not thread-safe. Thus
concurrent requests can access an empty slot in the builder's internal array.

Now using Lazy just as ApplicationImpl does.

Fixes:
 jakarta.el.ELException: java.lang.NullPointerException: Cannot invoke
 "jakarta.el.ELResolver.convertToType(...)" because "this.elResolvers[i]" is null
     at jakarta.el.ELContext.convertToType(ELContext.java:435)
     at org.glassfish.expressly.lang.EvaluationContext.convertToType(EvaluationContext.java:141)
     at org.glassfish.expressly.ValueExpressionImpl.getValue(ValueExpressionImpl.java:142)
     at org.apache.myfaces.application.ApplicationImpl.evaluateExpressionGet(ApplicationImpl.java:515)
     ...
 Caused by: java.lang.NullPointerException: ... "this.elResolvers[i]" is null
     at jakarta.el.CompositeELResolver.convertToType(CompositeELResolver.java:446)

Co-authored-by: Ulrich.Becker <ulrich.becker@adesso.de>