MYFACES-4380 LambdaBeanELResolver: Fix PropertyNotFoundException condition.
PropertyNotFoundException was thrown if the name of the poperty
requested was null, but it should really be thrown when the property
itself is not found.  This patch changes the nullness check
accordingly.

Before:

    java.lang.NullPointerException: Cannot invoke "org.apache.myfaces.core.api.shared.lang.PropertyDescriptorWrapper.getWrapped()" because "pd" is null
	at org.apache.myfaces.el.resolver.LambdaBeanELResolver.getValue(LambdaBeanELResolver.java:78)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:136)

After:

    javax.el.PropertyNotFoundException: Property [x] not found on type [com.example.FooBar_ClientProxy]
	at org.apache.myfaces.el.resolver.LambdaBeanELResolver.getPropertyDescriptor(LambdaBeanELResolver.java:162)
	at org.apache.myfaces.el.resolver.LambdaBeanELResolver.getValue(LambdaBeanELResolver.java:72)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:136)